# Day 9

In [1]:
# first, calculate size of grid

f = open('example9', 'r')

rl = 1
ud = 1
min_rl = 0
min_ud = 0
max_rl = 0
max_ud = 0

while True: 
    line = f.readline()
    if not line:
        break
    if line == '\n': 
        break
    
    if line[0] == 'R':
        rl += int(line[2:-1])
    elif line[0] == 'L':
        rl += -int(line[2:-1])
    elif line[0] == 'U': 
        ud += int(line[2:-1])
    elif line[0] == 'D': 
        ud += -int(line[2:-1])
        
    if rl > max_rl:
        max_rl = rl
    if ud > max_ud: 
        max_ud = ud
    if rl < min_rl:
        min_rl = rl
    if ud < min_ud: 
        min_ud = ud

print(min_rl, min_ud, max_rl, max_ud)

0 0 6 5


In [2]:
# track values on a grid
import numpy as np
grid = np.zeros((max_rl - min_rl, max_ud - min_ud))
print(grid.shape)

(6, 5)


In [3]:
head_pos = (-min_rl, -min_ud)
tail_pos = (-min_rl, -min_ud)
print(head_pos, tail_pos)

(0, 0) (0, 0)


In [4]:
# then, move head and tail and track their location

f = open('input9', 'r')

def move_head(head_pos, direction):
    '''
    function parses command and moves head
    returns new_head_pos as tuple
    '''
    hi = head_pos[0]
    hj = head_pos[1]
    if direction == 'R':
        hi += 1
    elif direction == 'L':
        hi += -1
    elif direction == 'U': 
        hj += 1
    elif direction == 'D': 
        hj += -1
    return (hi, hj)

def move_tail(head_pos, tail_pos):
    '''
    function moves tail given head (post move) and tail positions
    head_pos must be tuple
    tail_pos must be tuple
    returns new_tail_pos as tuple
    '''
    
    hi, hj = head_pos
    ti, tj = tail_pos 
    newi = tail_pos[0]
    newj = tail_pos[1]
    
    if abs(hi - ti) > 2: 
        print('Tail is too far away?')
    if abs(hj - tj) > 2: 
        print('Tail is too far away?')
    
    if hi == ti: # head and tail are in the same row
        if hj - tj == 2: 
            newi = ti
            newj = tj + 1
        elif hj - tj == -2: 
            newi = ti
            newj = tj - 1
    elif hj == tj: # head and tail are in the same column
        if hi - ti == 2: 
            newi = ti + 1
            newj = tj
        elif hi - ti == -2: 
            newi = ti - 1
            newj = tj
    elif hi - ti == 2:
        newi = hi - 1
        newj = hj
    elif hi - ti == -2: 
        newi = hi + 1
        newj = hj
    elif hj - tj == 2: 
        newi = hi
        newj = hj - 1
    elif hj - tj == -2: 
        newi = hi
        newj = hj + 1
   
    return (newi, newj)

while True: 
    line = f.readline()
    if not line:
        break
    if line == '\n': 
        break
        
    if tail_pos[0] < 0 or tail_pos[1] < 0: 
        print(head_pos, tail_pos)
        print("something has gone terribly wrong")
    
    try: 
        for i in range(int(line[2:-1])):
            head_pos = move_head(head_pos, line[0])
            tail_pos = move_tail(head_pos, tail_pos)
            grid[tail_pos[0], tail_pos[1]] = 1
    except: 
        print(head_pos, tail_pos)
        break

(0, -2) (0, -1)
something has gone terribly wrong
(2, -2) (1, -2)
something has gone terribly wrong
(1, -2) (1, -2)
something has gone terribly wrong
(1, 0) (1, -1)
something has gone terribly wrong
(1, -1) (1, -1)
something has gone terribly wrong
(-2, 2) (-1, 2)
something has gone terribly wrong
(-2, 1) (-1, 2)
something has gone terribly wrong
(-2, 3) (-1, 2)
something has gone terribly wrong
(-3, 3) (-2, 3)
something has gone terribly wrong
(-2, 3) (-2, 3)
something has gone terribly wrong
(-2, 2) (-2, 3)
something has gone terribly wrong
(-4, 2) (-3, 2)
something has gone terribly wrong
(-4, 0) (-4, 1)
something has gone terribly wrong
(-6, 0) (-5, 0)
something has gone terribly wrong
(-5, 0) (-5, 0)
something has gone terribly wrong
(-7, 0) (-6, 0)
something has gone terribly wrong
(-7, 2) (-7, 1)


In [5]:
print(grid)

[[1. 1. 0. 0. 1.]
 [1. 0. 0. 1. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]


In [6]:
print(sum(sum(grid)))

10.0


## ChatGPT solution

The typical. I asked if it could solve the problem for me in Python. 

In [7]:
# Rope physics simulation

# Store the starting positions of the head and tail
head_pos = (0, 0)
tail_pos = (0, 0)

# Keep track of the positions visited by the tail
tail_positions = [tail_pos]

# Open the input file
with open("input9") as f:
  # Read the moves from the file
  moves = f.read().strip().split("\n")

# Loop through the moves
for move in moves:
  # Parse the move into a direction and number of steps
  direction = move[0]
  steps = int(move[1:])

  # Update the position of the head
  if direction == "R":
    head_pos = (head_pos[0] + steps, head_pos[1])
  elif direction == "L":
    head_pos = (head_pos[0] - steps, head_pos[1])
  elif direction == "U":
    head_pos = (head_pos[0], head_pos[1] + steps)
  elif direction == "D":
    head_pos = (head_pos[0], head_pos[1] - steps)

  # Update the position of the tail
  if head_pos[0] == tail_pos[0] or head_pos[1] == tail_pos[1]:
    # The head and tail are in the same row or column, so the tail
    # moves one step in the same direction as the head
    tail_pos = (tail_pos[0] + head_pos[0] - tail_pos[0], tail_pos[1] + head_pos[1] - tail_pos[1])
  else:
    # The head and tail are not in the same row or column, so the tail
    # moves one step diagonally to keep up with the head
    tail_pos = (tail_pos[0] + 1 if head_pos[0] > tail_pos[0] else tail_pos[0] - 1, tail_pos[1] + 1 if head_pos[1] > tail_pos[1] else tail_pos[1] - 1)

  # Add the new position of the tail to the list of tail positions
  tail_positions.append(tail_pos)

# Compute the sum of the positions visited by the tail
sum_of_tail_positions = sum(1 for x, y in tail_positions)

# Print the sum
print(sum_of_tail_positions)

2001


God, this is miserable. ChatGPT is not getting it off the bat. I may have to modify my strategy of conversing with it to figure out 

# Part 2

In [8]:
# first, calculate size of grid

f = open('example9-2', 'r')

rl = 1
ud = 1
min_rl = 0
min_ud = 0
max_rl = 0
max_ud = 0

while True: 
    line = f.readline()
    if not line:
        break
    if line == '\n': 
        break
    
    if line[0] == 'R':
        rl += int(line[2:-1])
    elif line[0] == 'L':
        rl += -int(line[2:-1])
    elif line[0] == 'U': 
        ud += int(line[2:-1])
    elif line[0] == 'D': 
        ud += -int(line[2:-1])
        
    if rl > max_rl:
        max_rl = rl
    if ud > max_ud: 
        max_ud = ud
    if rl < min_rl:
        min_rl = rl
    if ud < min_ud: 
        min_ud = ud

print(min_rl, min_ud, max_rl, max_ud)

-10 -4 15 16


In [9]:

def move_head(head_pos, direction):
    '''
    function parses command and moves head
    returns new_head_pos as tuple
    '''
    hi = head_pos[0]
    hj = head_pos[1]
    if direction == 'R':
        hi += 1
    elif direction == 'L':
        hi += -1
    elif direction == 'U': 
        hj += 1
    elif direction == 'D': 
        hj += -1
    return (hi, hj)

def move_tail(head_pos, tail_pos):
    '''
    function moves tail given head (post move) and tail positions
    head_pos must be tuple
    tail_pos must be tuple
    returns new_tail_pos as tuple
    '''
    
    hi, hj = head_pos
    ti, tj = tail_pos 
    newi = tail_pos[0]
    newj = tail_pos[1]
    
    if abs(hi - ti) > 2: 
        print('Tail is too far away?')
    if abs(hj - tj) > 2: 
        print('Tail is too far away?')
    
    if hi == ti: # head and tail are in the same row
        if hj - tj == 2: 
            newi = ti
            newj = tj + 1
        elif hj - tj == -2: 
            newi = ti
            newj = tj - 1
    elif hj == tj: # head and tail are in the same column
        if hi - ti == 2: 
            newi = ti + 1
            newj = tj
        elif hi - ti == -2: 
            newi = ti - 1
            newj = tj
    elif hi - ti == 2:
        newi = hi - 1
        newj = hj
    elif hi - ti == -2: 
        newi = hi + 1
        newj = hj
    elif hj - tj == 2: 
        newi = hi
        newj = hj - 1
    elif hj - tj == -2: 
        newi = hi
        newj = hj + 1
   
    return (newi, newj)

In [10]:
# track values on a grid
import numpy as np
grid = np.zeros((max_rl - min_rl, max_ud - min_ud))
print(grid.shape)

(25, 20)


In [11]:
rope_length = 10
rope = []
for i in range(rope_length):
    rope.append((-min_rl, -min_ud))
print(rope)

[(10, 4), (10, 4), (10, 4), (10, 4), (10, 4), (10, 4), (10, 4), (10, 4), (10, 4), (10, 4)]


In [14]:
# then, move head and tail and track their location

f = open('example9-2', 'r')

while True: 
    line = f.readline()
    if not line:
        break
    if line == '\n': 
        break
    
    # try:
    for i in range(int(line[2:-1])):
        for j in range(rope_length):
            if j == 0:
                rope[0] = move_head(rope[0], line[0])
            else: 
                rope[j] = move_tail(rope[j-1], rope[j])
        grid[rope[rope_length][0], rope[rope_length][1]] = 1
    # except: 
    #     print(rope)
    #     break

IndexError: list index out of range

In [13]:
print(grid)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [88]:
print(sum(sum(grid)))

36.0
